services:
  postgres:
    image: postgres:latest
    container_name: go_auth
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: go_auth_adminer
    ports:
      - "8080:8080"

volumes:
  postgres:      